### ISSUE TITLE
Foundation / CLI Templates / Create CLI Template Groups - Wrong payload in body

### ISSUE THREAD

**Issue by p-sirois** [fortinet-solutions-cse/postman_collections#11]
The payload in the call is not following the [doc](https://fndn.fortinet.net/index.php?/fortiapi/5-fortimanager/2768/5/pm/config/cli/).

The format in the call is
 ```
           "data": [
                {
                    "name": "Hub-Template",
                    "member": [
                        "01-Hub-Underlay",
                        "02-Hub-Overlay",
                        "03-Hub-Routing",
                        "04-Hub-MultiRegion"
                    ],
                    "scope member": [
                        {
                            "is group": 1,
                            "name": "Hubs"
                        }
                    ]
                },
                {
                    "name": "Edge-Template",
                    "member": [
                        "01-Edge-Underlay",
                        "02-Edge-Overlay",
                        "03-Edge-Routing"
                    ],
                    "scope member": [
                        {
                            "is group": 1,
                            "name": "Edge"
                        }
                    ]
                }
            ]
```

This should actually be

```
            "data": [
                {
                    "name": "Edge-Template",
                    "description": "",
                    "member": [
                        "01-Edge-Underlay",
                        "02-Edge-Overlay",
                        "03-Edge-Routing"
                    ],
                    "variables": [
                        "hostname",
                        "lan_ip",
                        "loopback",
                        "profile",
                        "region"
                    ]
                },
                {
                    "name": "Hub-Template",
                    "description": "",
                    "member": [
                        "01-Hub-Underlay",
                        "02-Hub-Overlay",
                        "03-Hub-Routing",
                        "05-Hub-IntraRegion"
                    ],
                    "variables": [
                        "hostname",
                        "lan_ip",
                        "loopback",
                        "profile",
                        "region"
                    ]
                } 
```

**Comment by dmitryperets** [comment]
Hi @p-sirois, 

The `variables` parameter lists the Metadata Variables used by the CLI Template. They are displayed in the FMG GUI, there is a column for them. To be honest, I don't think they are used for the CLI Template Groups, but only for the individual CLI Templates. So not sure why the syntax has them. 

Anyway, I don't think there is a point to manually set those values. The FMG will set them automatically, once you import the templates. 

As for the `scope member` parameter that we are using - although not documented, it does work. A more "official" way would probably be to run a separate call modifying the `scope member` - essentially, assigning the Template Group to a Device Group. But we've figured out that FMG accepts it all in one call without issues. 

Have you experienced any issue with these calls?
Or is your concern only about the mismatch with the FNDN documentation?

**Comment by p-sirois** [comment]
The call, as is, failed on FMG 7.2.4
```

{
    "result": [
        {
            "status": {
                "code": -10000,
                "message": "cli/template-group/Hub-Template/ : invalid value"
            },
            "url": "/pm/config/adom/CustomerA/obj/cli/template-group"
        }
    ],
    "id": 1
}
```

**Comment by dmitryperets** [comment]
When you are running this call, are you sure that all the mentioned CLI Templates already exist in the FMG? 

Make sure that you see the following Jinja CLI Templates:
                       "01-Hub-Underlay",
                       "02-Hub-Overlay",
                       "03-Hub-Routing",
                       "04-Hub-MultiRegion"

Also make sure you have the Device Group called "Hubs". 

I've just tested on our standard hands-on lab instance running FMG 7.2.4 - and the call seems to work fine. 
But note that there is a known GUI issue with that FMG release which sometimes uploads only some of the template files that you are importing. That is why I suggest to make sure that, before you run this API call, you actually see all the above CLI Templates in the list. 

If I try to run the call without having all these CLI Templates, I get exactly the same error code as yours. 
But when all the CLI Templates are there, the call runs successfully.

**Comment by p-sirois** [comment]
That is it, I was able to replicate the behavior on the CustomerB section of the lab. You are correct with the GUI bug when we upload multiple templates. That was simply it.
