### ISSUE TITLE
task 21 policy srcintf changed

### ISSUE THREAD

**Issue by fortinetps** [fortinet-solutions-cse/postman_collections#4]
Just FYI, in this commit, 
https://github.com/fortinet-solutions-cse/postman_collections/commit/a976a77f32574cb7ae809790fc501dda16d46443#diff-e62419e48abebbb57950f6e12832004e

We updated task#21, which is to create/update the branch FGT firewall policy package, the firewall policy's interface updated from the original "Client-BR1" and "WirelessVLAN" to the new "vl_lan" and "vl_fap_mgmt". 

But in the FortiPoC, SD-BRANCH-MSP-WS-2.2-622GA (MSSP SD-WAN Workshop), we are still using "Client-BR1" and "WirelessVLAN"

I think we should keep the consistency. 

FYI, I synced my "SD-BRANCH-MSP-WS-2.2-622GA (MSSP SD-WAN Workshop)" from FortiPoC, wondering that might be an older version...

Thanks!
Don

**Comment by mamunozgonzalez** [comment]
Thanks Don for your feedback. We have incorporated those changes into the current ongoing work and will be released shortly with next version.

Feel free to let us know if there is any other issue (or reopen this one if any of the mentioned names appear).
